[workspace]
resolver = "2"
members = [
    "reweave-core",
    "reweave-macro",
    "reweave-tangle",
    "reweave-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Gianni Ferrarotti <gianni.ferrarotti@gmail.com>"]
license = "0BSD OR MIT OR Apache-2.0"

[workspace.dependencies]
clap = { version = "4.6", features = ["derive"] }
memchr = "2"
miette = { version = "7", features = ["fancy"] }
monty = { git = "https://github.com/pydantic/monty", tag = "v0.0.23" }
monty-types = { git = "https://github.com/pydantic/monty", tag = "v0.0.23" }
pretty_assertions = "1.4"
regex = "1.13"
tempfile = "3.27"
thiserror = "2.0"
walkdir = "2"

reweave-core = { path = "reweave-core" }
reweave-macro = { path = "reweave-macro" }
reweave-tangle = { path = "reweave-tangle" }
